# Generated by Django 5.2.8 on 2026-01-02 12:26

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Reference')),
                ('staff_id', models.PositiveIntegerField(verbose_name='Staff ID')),
                ('staff_name', models.CharField(help_text='Cached staff name', max_length=200, verbose_name='Staff Name')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Gross Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax Withheld')),
                ('adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Manual adjustments (positive or negative)', max_digits=10, verbose_name='Adjustments')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Net Amount')),
                ('transaction_count', models.PositiveIntegerField(default=0, verbose_name='Transaction Count')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('payroll', 'Added to Payroll'), ('other', 'Other')], max_length=20, verbose_name='Payment Method')),
                ('payment_reference', models.CharField(blank=True, help_text='Check number, transfer ID, etc.', max_length=100, verbose_name='Payment Reference')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('approved_by_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Approved By')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('paid_by_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Paid By')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Payout',
                'verbose_name_plural': 'Commission Payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rule Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('rule_type', models.CharField(choices=[('flat', 'Flat Amount'), ('percentage', 'Percentage'), ('tiered', 'Tiered (based on sales volume)')], default='percentage', max_length=20, verbose_name='Type')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage rate or flat amount', max_digits=10, verbose_name='Rate')),
                ('staff_id', models.PositiveIntegerField(blank=True, help_text='Apply to specific staff member', null=True, verbose_name='Staff ID')),
                ('service_id', models.PositiveIntegerField(blank=True, help_text='Apply to specific service', null=True, verbose_name='Service ID')),
                ('category_id', models.PositiveIntegerField(blank=True, help_text='Apply to specific category', null=True, verbose_name='Category ID')),
                ('product_id', models.PositiveIntegerField(blank=True, help_text='Apply to specific product', null=True, verbose_name='Product ID')),
                ('tier_thresholds', models.JSONField(blank=True, default=list, help_text='List of {min_amount, max_amount, rate} for tiered rules', verbose_name='Tier Thresholds')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='Effective From')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='Effective Until')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority rules are applied first', verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Rule',
                'verbose_name_plural': 'Commission Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Default Commission Rate (%)')),
                ('calculation_basis', models.CharField(choices=[('gross', 'Gross Sales'), ('net', 'Net Sales (after discounts)'), ('profit', 'Profit Margin')], default='net', help_text='What the commission percentage is based on', max_length=20, verbose_name='Calculation Basis')),
                ('payout_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='monthly', max_length=20, verbose_name='Payout Frequency')),
                ('payout_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month/week for payouts', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Payout Day')),
                ('minimum_payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum amount required for payout', max_digits=10, verbose_name='Minimum Payout Amount')),
                ('apply_tax_withholding', models.BooleanField(default=False, verbose_name='Apply Tax Withholding')),
                ('tax_withholding_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Tax Withholding Rate (%)')),
                ('show_commission_on_receipt', models.BooleanField(default=False, verbose_name='Show Commission on Receipt')),
                ('show_pending_commission', models.BooleanField(default=True, verbose_name='Show Pending Commission to Staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commissions Configuration',
                'verbose_name_plural': 'Commissions Configuration',
            },
        ),
        migrations.CreateModel(
            name='CommissionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.PositiveIntegerField(verbose_name='Staff ID')),
                ('staff_name', models.CharField(help_text='Cached staff name', max_length=200, verbose_name='Staff Name')),
                ('adjustment_type', models.CharField(choices=[('bonus', 'Bonus'), ('correction', 'Correction'), ('deduction', 'Deduction'), ('refund_adjustment', 'Refund Adjustment'), ('other', 'Other')], default='correction', max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for additions, negative for deductions', max_digits=10, verbose_name='Amount')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('adjustment_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('created_by_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_list', to='commissions.commissionpayout', verbose_name='Payout')),
            ],
            options={
                'verbose_name': 'Commission Adjustment',
                'verbose_name_plural': 'Commission Adjustments',
                'ordering': ['-adjustment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.PositiveIntegerField(verbose_name='Staff ID')),
                ('staff_name', models.CharField(help_text='Cached staff name', max_length=200, verbose_name='Staff Name')),
                ('sale_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sale ID')),
                ('sale_reference', models.CharField(blank=True, max_length=100, verbose_name='Sale Reference')),
                ('appointment_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Appointment ID')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale Amount')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Commission Rate (%)')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Commission Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax Withheld')),
                ('net_commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Commission')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('adjusted', 'Adjusted')], default='pending', max_length=20, verbose_name='Status')),
                ('transaction_date', models.DateField(default=datetime.date.today, verbose_name='Transaction Date')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('approved_by_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Approved By')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='commissions.commissionpayout', verbose_name='Payout')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='commissions.commissionrule', verbose_name='Rule')),
            ],
            options={
                'verbose_name': 'Commission Transaction',
                'verbose_name_plural': 'Commission Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
